# Generated by Django 2.0.2 on 2018-06-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='글 제목')),
                ('link', models.URLField(verbose_name='글 링크')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='글 요약')),
                ('will_summary', models.BooleanField(verbose_name='글 요약할 것인지')),
                ('rate', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='점수')),
                ('enable', models.BooleanField(default=True, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시점')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시점')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'verbose_name': '글 및 글 요약',
                'verbose_name_plural': '글 및 글 요약',
            },
        ),
        migrations.CreateModel(
            name='ArticleHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'verbose_name': '테이블 연결: Article, Tag',
                'verbose_name_plural': '테이블 연결: Article, Tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='태그 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='태그 생성 시점')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
            },
        ),
        migrations.AddField(
            model_name='articlehastag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tag'),
        ),
    ]
